apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-example
  labels:
    app: cicd-example
spec:
  replicas: 2 # pod count
  selector:
    matchLabels:
      app: cicd-example
  template:
    metadata:
      name: cicd-example
      labels:
        app: cicd-example
    spec:
      containers:
        - name: cicd-example
          image: local/cicd-example:latest
          imagePullPolicy: Never 
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-example
  labels:
    app: cicd-example
spec:
  selector:
    app: cicd-example
  ports:
    - name: http
      port: 8080 # where the service is running
      targetPort: 8080 # the port exposed by the service
  type: NodePort # type of service